"""empty message

Revision ID: 37a72b5613a8
Revises: None
Create Date: 2014-02-07 17:12:10.225000

"""

# revision identifiers, used by Alembic.
revision = '37a72b5613a8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
