"""empty message

Revision ID: 3d8aa4911708
Revises: 37a72b5613a8
Create Date: 2014-02-07 17:37:00.298000

"""

# revision identifiers, used by Alembic.
revision = '3d8aa4911708'
down_revision = '37a72b5613a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=350), nullable=True),
    sa.Column('password_hash', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mail_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=350), nullable=True),
    sa.Column('is_authorized', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column(u'message', sa.Column('mail_account_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'message', 'mail_account_id')
    op.drop_table('mail_account')
    op.drop_table('user')
    ### end Alembic commands ###
